# Generated by Django 3.0.6 on 2020-05-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='baba',
            field=models.TextField(default=''),
        ),
    ]
