# Generated by Django 3.1.7 on 2021-04-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_slider_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slider_post',
            field=models.BooleanField(blank=True, null=True, verbose_name='slider_post'),
        ),
    ]
