# Generated by Django 3.1.7 on 2021-05-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id']},
        ),
    ]
