# Generated by Django 3.1.7 on 2021-04-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210425_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
