# Generated by Django 3.2.5 on 2021-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210712_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='users/person-icon-blue-7560_vad8ci.png', upload_to='comment/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/uploads/blog_tckati.jpg', upload_to='uploads/', verbose_name='image'),
        ),
    ]
