# Generated by Django 3.2.5 on 2021-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20210712_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slider_post',
            field=models.BooleanField(default=False, verbose_name='slider_post'),
        ),
    ]
