# Generated by Django 3.1.7 on 2021-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
        ('users', '0003_auto_20210402_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='category_like',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category_like',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
