# Generated by Django 3.1.7 on 2021-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
        ('users', '0005_auto_20210402_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category_like',
            field=models.ManyToManyField(default='food', to='posts.Category'),
        ),
    ]
