# Generated by Django 3.1.7 on 2021-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210403_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='birth_day'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='person-icon-blue-7560.png', null=True, upload_to='users', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='slug'),
        ),
    ]
