# Generated by Django 3.1.7 on 2021-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210403_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='person-icon-blue-7560.png', null=True, upload_to='users/', verbose_name='image'),
        ),
    ]
