# Generated by Django 3.1.7 on 2021-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210404_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='users/person-icon-blue-7560_vad8ci.png', null=True, upload_to='users/', verbose_name='image'),
        ),
    ]
