# Generated by Django 3.1.7 on 2021-04-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myarchive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='main_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
