# Generated by Django 3.1.7 on 2021-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarchive', '0002_auto_20210402_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='hit',
            field=models.PositiveIntegerField(default=0, verbose_name='hit'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publishing_date'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='slider_post',
            field=models.BooleanField(default=False, verbose_name='slider_post'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='slug',
            field=models.SlugField(default='slug', editable=False, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
