# Generated by Django 3.1.7 on 2021-05-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_post_likes'),
        ('myarchive', '0003_auto_20210403_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post'),
        ),
    ]
