# Generated by Django 3.1.7 on 2021-05-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarchive', '0004_archive_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['id']},
        ),
    ]
