# Generated by Django 3.1.7 on 2021-05-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarchive', '0007_auto_20210523_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='post',
        ),
    ]
