# Generated by Django 3.1.7 on 2021-05-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210523_1328'),
        ('myarchive', '0008_remove_archive_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='category',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='content',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='hit',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='image',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='publishing_date',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='slider_post',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='title',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='user',
        ),
        migrations.AddField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
