# Generated by Django 3.1.7 on 2021-05-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210523_1328'),
        ('myarchive', '0009_auto_20210523_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='posts.category'),
        ),
        migrations.AddField(
            model_name='archive',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='archive',
            name='hit',
            field=models.PositiveIntegerField(default=0, verbose_name='hit'),
        ),
        migrations.AddField(
            model_name='archive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='archive',
            name='publishing_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='publishing_date'),
        ),
        migrations.AddField(
            model_name='archive',
            name='slider_post',
            field=models.BooleanField(default=False, verbose_name='slider_post'),
        ),
        migrations.AddField(
            model_name='archive',
            name='slug',
            field=models.SlugField(default='slug', editable=False, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='archive',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='archives', to='posts.Tag'),
        ),
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post'),
        ),
    ]
