# Generated by Django 3.1.7 on 2021-05-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarchive', '0010_auto_20210523_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='tag',
        ),
    ]
