# Generated by Django 3.1.7 on 2021-05-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210523_1328'),
        ('myarchive', '0011_remove_archive_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='posts.post'),
        ),
    ]
