# Generated by Django 3.1.7 on 2021-05-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210523_1328'),
        ('myarchive', '0012_auto_20210523_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to='posts.post'),
        ),
    ]
