# Generated by Django 3.1.7 on 2021-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarchive', '0015_auto_20210523_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.PositiveIntegerField(default=0, verbose_name='user'),
        ),
    ]
