# Generated by Django 3.2.5 on 2021-08-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_slider_post'),
        ('myarchive', '0021_alter_archive_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='post',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.post'),
        ),
    ]
